# Generated by Django 4.0.4 on 2022-05-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
