# Generated by Django 4.0.4 on 2022-05-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
