# Generated by Django 4.0.4 on 2022-05-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0012_appointment_booking_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_no',
            field=models.CharField(max_length=100),
        ),
    ]
