# Generated by Django 4.0.4 on 2022-05-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0013_alter_appointment_booking_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
