# Generated by Django 4.0.4 on 2022-05-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0022_subscription_plan_pricing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pricing',
        ),
        migrations.DeleteModel(
            name='Subscription_plan',
        ),
    ]
