# Generated by Django 4.0.4 on 2022-05-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0026_checkout_sub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
