# Generated by Django 4.0.4 on 2022-05-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0028_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
