# Generated by Django 4.0.4 on 2022-05-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0034_remove_appointment_appt_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
