# Generated by Django 4.0.4 on 2022-05-14 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0035_appointment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='price',
        ),
        migrations.CreateModel(
            name='Appointment_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=10)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicale.appointment')),
            ],
            options={
                'verbose_name': 'Appointment_Price',
                'verbose_name_plural': 'Appointment_Prices',
                'db_table': 'appointment_price',
                'managed': True,
            },
        ),
    ]
