# Generated by Django 4.0.4 on 2022-05-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0036_remove_appointment_price_appointment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment_price',
            name='price',
        ),
    ]
