# Generated by Django 4.0.4 on 2022-05-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0037_remove_appointment_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_price',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
