# Generated by Django 4.0.4 on 2022-05-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0038_appointment_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_price',
            name='price',
            field=models.IntegerField(),
        ),
    ]
