# Generated by Django 4.0.4 on 2022-05-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0041_appointment_appointment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment_price',
            name='appointment',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Appointment_Price',
        ),
    ]
