# Generated by Django 4.0.4 on 2022-05-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0044_alter_appointment_price_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_price',
            name='booking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment_price',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
