# Generated by Django 4.0.4 on 2022-05-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0045_alter_appointment_price_booking_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Appointment_Price',
        ),
    ]
