# Generated by Django 4.0.4 on 2022-05-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0049_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
