# Generated by Django 4.0.4 on 2022-05-22 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0051_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
