# Generated by Django 4.0.4 on 2022-05-22 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0053_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
