# Generated by Django 4.0.4 on 2022-05-24 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0055_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
