# Generated by Django 4.0.4 on 2022-06-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0060_alter_appointment_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
