# Generated by Django 4.0.4 on 2022-06-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0062_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='price',
            field=models.CharField(max_length=2),
        ),
    ]
