# Generated by Django 4.0.4 on 2022-06-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0064_alter_appointment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship_sub',
            name='things_bought',
            field=models.CharField(blank=True, default='john', max_length=300, null=True),
        ),
    ]
