# Generated by Django 4.0.4 on 2022-06-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0065_ship_sub_things_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship_sub',
            name='things_bought',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
