# Generated by Django 4.0.4 on 2022-07-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0067_alter_appointment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='follow_up',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
