# Generated by Django 4.0.4 on 2022-04-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, default='pharmacy.jpg', null=True, upload_to='pharmacy')),
                ('drug_type', models.CharField(max_length=150, unique=True)),
                ('min_order', models.IntegerField(default=1)),
                ('max_order', models.IntegerField(default=5)),
                ('price', models.IntegerField()),
                ('display', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pharmacy',
                'verbose_name_plural': 'Pharmacys',
                'db_table': 'pharmacy',
                'managed': True,
            },
        ),
    ]
