# Generated by Django 4.0.4 on 2022-05-01 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='drug_type',
        ),
        migrations.DeleteModel(
            name='Drug_type',
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
    ]
