# Generated by Django 4.0.4 on 2022-05-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
    ]
