# Generated by Django 4.0.4 on 2022-05-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='effect',
            field=models.TextField(default='o'),
        ),
    ]
