# Generated by Django 4.0.4 on 2022-05-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacycart', '0004_remove_drugscart_pharmacy_remove_drugscart_user_and_more'),
        ('pharmacy', '0012_alter_description_effect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='drug_type',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Drug_type',
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
    ]
