# Generated by Django 4.0.4 on 2022-05-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='advice',
            field=models.TextField(default='o'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='effect',
            field=models.TextField(default='o'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='how_to_use',
            field=models.TextField(default='o'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='ingredient',
            field=models.CharField(blank=True, default='o', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='overview',
            field=models.TextField(default='o'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='supplements',
            field=models.BooleanField(default='o'),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
