# Generated by Django 4.0.4 on 2022-05-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_pharmacy_advice_pharmacy_effect_pharmacy_how_to_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='advice',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='effect',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='how_to_use',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='ingredient',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='overview',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='supplements',
            field=models.BooleanField(),
        ),
    ]
