# Generated by Django 4.0.4 on 2022-05-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0016_alter_pharmacy_advice_alter_pharmacy_effect_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Prescrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.FileField(upload_to='prescriptions')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Upload_Prescrip',
                'verbose_name_plural': 'Upload_Prescrips',
                'db_table': 'upload_prescrip',
                'managed': True,
            },
        ),
    ]
