# Generated by Django 4.0.4 on 2022-05-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0017_upload_prescrip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload_Prescrip',
        ),
    ]
