# Generated by Django 4.0.4 on 2022-04-25 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Process', 'Process'), ('closed', 'Closed')], default='new', max_length=100)),
                ('closed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact-us',
                'verbose_name_plural': 'Contact-us',
                'db_table': 'contact-us',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_weight', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_height', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='profile')),
                ('medication', models.BooleanField(blank=True, null=True)),
                ('disease', models.CharField(blank=True, max_length=100, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('family', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('records', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profile',
                'managed': True,
            },
        ),
    ]
