# Generated by Django 4.0.4 on 2022-05-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_recovery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recovery',
        ),
    ]
