# Generated by Django 4.0.4 on 2022-06-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
