# Generated by Django 4.0.4 on 2022-05-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
